### ISSUE TITLE
any clues why the newick format from pyglottolog doesn't read well into R?

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#101]
Does anyone have any ideas as to why I'm getting two different results when reading in these two Glottolog newick files into R:

1. [tree_glottolog_newick.txt ](https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/tree_glottolog_newick.txt)-file 
2. a file I created by saving the output from running` glottolog newick ural1272`

The first one reads in just fine with [ape::read.tree()](https://www.rdocumentation.org/packages/ape/versions/5.2/topics/read.tree), but the second reads in as entirely empty. No error messages though, it's just that the variable is NULL.

I'm trying to teach myself to use pyglottolog, with help from @chrzyki . I thought I'd just render a newick file and see how it goes, just as a simple practice example. I can't really understand why this isn't working. Are there different dialects of newick/new hampshire tree formatting employed? Am I doing something else wrong?

I know that you're not responsible for the ape package in R, naturally. But, if anyone has any clues to what would be different about these two files I'd be very grateful.

**Comment by xrotwang** [comment]
Does the latter tree end with semicolon?

Hedvig Skirgård <notifications@github.com> schrieb am Fr., 5. Okt. 2018,
12:08:

**Comment by SimonGreenhill** [comment]
I think it's [this problem](https://github.com/D-PLACE/dplace-data/issues/81)

**Comment by SimonGreenhill** [comment]
Actually, no, it's just the semi-colon :)

**Comment by xrotwang** [comment]
So, all good? If not, that should have been an issue in clld/glottolog
anyway 😉

Simon J Greenhill <notifications@github.com> schrieb am Fr., 5. Okt. 2018,
13:00:

**Comment by HedvigS** [comment]
Aha, it does not! Added one, and now it reads in just fine. Thanks @xrotwang 

What's the reason it wasn't there before?

**Comment by HedvigS** [comment]
Should I expect to have to add one in each time, or will something else change?

**Comment by SimonGreenhill** [comment]
every time.

**Comment by HedvigS** [comment]
Right, okay. I'll just do a pipe where I read it in as a text file, add a semi-colon and then read it in as a tree with ape. Or just read in [this file](url
https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/tree_glottolog_newick.txt) or [the d-place versions](https://github.com/D-PLACE/dplace-data/tree/master/phylogenies). I guess that since the parentheses must balance, the semi-colon is technically superfluous. But, it's still the expected format.

The pyglottolog tools (besides newick), I think, are meant for a user group that isn't me. Now that I understand this one, I think that's it for me when it comes to pyglottolog.

**Comment by HedvigS** [comment]
The trees in newick format that are downloadable from the website still lack a semicolon at the end. 

Example: [https://glottolog.org/resource/languoid/id/mixt1422.newick.txt](https://glottolog.org/resource/languoid/id/mixt1422.newick.txt)

**Comment by HedvigS** [comment]
If this is the set-up continusly, maybe it can be described somewhere? Others are having the same issue.

**Comment by xrotwang** [comment]
fixed now

**Comment by HedvigS** [comment]
Thanks
