### ISSUE TITLE
Don't display alternative names of type "hhbib_lgcode"

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#104]
Currently, the web app displays alternative names of type `hhbib_lgcode`, e.g. for [Swedish](https://glottolog.org/resource/languoid/id/swed1254). These names should not be displayed, because they have different semantics - i.e. they are not really alternative names, but rather names that appear in reference titles which should trigger association of the reference with the language.

**Comment by d97hah** [comment]
Right, they should be very useful in searching (human and automated) but
not suitable for display.

Pada tanggal Kam, 13 Des 2018 pukul 16.05 Robert Forkel <
notifications@github.com> menulis:
