### ISSUE TITLE
Dialect-level languoids shown as 'safe' by default, should rather be 'unknown' (or at least <= parent.status)

### ISSUE THREAD

**Issue by d97hah** [clld/glottolog3#112]
Possibly solution, change initdb.py Line 275:
 
status=models.LanguoidStatus.get(lang.endangerment.name if lang.endangerment else 'safe'),

to

status=models.LanguoidStatus.get(lang.endangerment.name if lang.endangerment else 'unknown'),

**Comment by xrotwang** [comment]
Endangerment info is now not inherited at all.
