### ISSUE TITLE
Number of languages listed on "About languoids" omits isolates

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#114]
The number of languages (total and L1) listed on ["About languoids"](https://glottolog.org/glottolog/glottologinformation) is too low, because the isolates are omitted. This is presumably due to joining on `family_pk` (which is `NULL` for isolates) in order to compute counts for the "special" families.

**Comment by xrotwang** [comment]
@d97hah just noticed this somewhat embarrassing bug.

**Comment by d97hah** [comment]
That listing has had worse bugs before ;-)

Pada tanggal Sel, 18 Jun 2019 pukul 16.25 Robert Forkel <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
(That's one of the reasons I've added a separate Family_ID column in my sheet with more things separated out, I had isolates being omitted a few times in my R code before I realised it was because their Family_IDs were null :) .)
