### ISSUE TITLE
Update or remove refs number in dataset description

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#116]
The number here
https://github.com/clld/glottolog3/blob/101c0d8f090b0d069485fca4352016b9aa51ad60/glottolog3/templates/dataset/detail_html.mako#L60
is outdated and should be removed.

**Comment by HedvigS** [comment]
(I used that because I thought that was the preferred and de-duplicated number that you wanted people to reference. If I may, could it be replaced by a better number instead of removed? :) )
