### ISSUE TITLE
Add links to AIATSIS

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog3#118]
The Australian Institute of Aboriginal and Torres St. Islanders has a semi-official list of languages for Australia/Torres. Each language has its own code, e.g. https://collection.aiatsis.gov.au/austlang/language/S35, which would be nice to have linked.

They also publish all their name data here:
https://collection.aiatsis.gov.au/datasets/austlang/001

...which would be nice to add as well.

**Comment by xrotwang** [comment]
Moved to https://github.com/glottolog/glottolog/issues/429

**Comment by xrotwang** [comment]
Once we have the links in the data (see https://github.com/glottolog/glottolog/issues/429), AIATSIS needs to be added as `PartnerSite`.

**Comment by d97hah** [comment]
They don't explain this list anywhere (i.e., what kind of divisions) and
there are many names without reference to anything concrete. I won't be
matching it.

"A104","Pijikala","","Pijikala language A104","","","
https://collection.aiatsis.gov.au/austlang/language/a104"


Pada tanggal Sel, 22 Okt 2019 pukul 11.38 Simon J Greenhill <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Work has started, see https://github.com/glottolog/pyglottolog/blob/master/src/pyglottolog/links/aiatsis.py and will hopefully become more complete over time.
