### ISSUE TITLE
Modern Greek moribund?

### ISSUE THREAD

**Issue by VivaRado** [clld/glottolog3#131]
Agglomerated Endangerment Status (AES) Mentions that Modern Greek is considered moribund.

**Comment by xflr6** [comment]
Thanks. I think this would be better in https://github.com/glottolog/glottolog/issues (data repository).

**Comment by d97hah** [comment]
Thanks I thought I had fixed this a while ago, but apparently not. Will be
fixed for next version! H

Pada tanggal Min, 14 Feb 2021 pukul 13.03 Sebastian Bank <
notifications@github.com> menulis:
