### ISSUE TITLE
bibtex parsing doesn't remove {Enforced Capitals}

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog3#132]
Bibtex allows you to enforce capitalisation in the BibTeX record by wrapping the text in {BracKets} which will then render as "BracKets" rather than being lowercased by default. Some bib files contain this e.g. https://glottolog.org/resource/reference/id/473057

...which renders in the [tables of the webapp](https://glottolog.org/resource/languoid/id/germ1287) as:

```
Dialekt - {Nationaldialekt} - {Standardsprache}. {Vergeleichende} {Betrachtungen} zum deutsch-französischen {Kontakbereich} in der {Schweiz}, im {Elsaß} und in {Luxemburg}
```

Perhaps the bibtex to html renderer can replace `{}` within the table?

**Comment by xrotwang** [comment]
Should be done when loading the data into the db at https://github.com/clld/glottolog3/blob/2d448704d62de31425c13965f989d299fddbbf64/glottolog3/scripts/initializedb.py#L423

**Comment by xrotwang** [comment]
Almost all cases of `{` in titles come from https://github.com/glottolog/glottolog/blob/master/references/bibtex/bibliolux.bib , so I guess, I'll fix it there.
