### ISSUE TITLE
search not recognising glottocode

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#153]
When searching 3adt1234 in the top right search bar, I get the response:

"No matching languoids found for name part "3adt1234"

https://glottolog.org/glottolog?search=3adt1234

**Comment by xrotwang** [comment]
The pattern here 
https://github.com/clld/glottolog3/blob/4773988e43d6f504b91bab5b2b2c7e3cfbf5e3ec/glottolog3/views.py#L34 
must be replaced with the "official one" here 
https://github.com/glottolog/pyglottolog/blob/58ceca0676331ac724ba1eb4755e55f0fa459252/src/pyglottolog/languoids/models.py#L101
