### ISSUE TITLE
glottoscope aes overtime

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#155]
it is the case right that aes does not vary over time, but med does?
If so, could that be clarified in the year slider box in glottoscope? For example, by adding "there is historical information on descriptive status, but not endangerment status. Only descriptive status therefore varies over time."

**Comment by d97hah** [comment]
https://github.com/clld/glottolog3/pull/156

Pada Sel, 23 Jan 2024 pukul 21.48 Hedvig Skirgård ***@***.***>
menulis:

**Comment by xrotwang** [comment]
https://glottolog.org/langdoc/status/browser?macroarea=Africa&focus=ed#3/2.35/16.97
