### ISSUE TITLE
Could "threteaned" in glottoscope be yellow?

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#157]
Currently, in the glottoscope interface the legend has a green nuance for the category "threatened" which makes it hard to distinguish from "not endangered". Could this be changed to a yellow hue (for example #FBEB82)?

Shifting, moribund and nearly extinct are also very similar but that seems less of an issue.

**Comment by xrotwang** [comment]
That's part of the config data curated here: https://github.com/glottolog/glottolog/blob/master/config/aes_status.ini
So if we change this, it would have to happen with the next glottolog data version.

**Comment by HedvigS** [comment]
That sounds good to me :)!
If you wanna tweak the others so they're less similar I could give some suggstions too.

**Comment by xrotwang** [comment]
I'll probably go with a selection based on https://cran.r-project.org/web/packages/khroma/vignettes/tol.html#incandescent

**Comment by HedvigS** [comment]
For enough! As long as the "not endangered" and all the others are more distinct that'll be good. The step between "not endangered" and "threatened" ought to be larger than the other steps.

**Comment by xrotwang** [comment]
Will be online with Glottolog 5.0
