### ISSUE TITLE
Create a high level "Country" page

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog3#160]
Please create a high level "Country" page to show all the languages for a given country.

**Comment by xrotwang** [comment]
What about https://glottolog.org/glottolog/language.map.html?country=ID - accessed from the "Country" search on https://glottolog.org/glottolog ?

**Comment by SimonGreenhill** [comment]
Ahh, couldn't find that. That's exactly what I was after. Can this be made more visible (e.g. a link on the langoid page under the Countries subheading?)

**Comment by SimonGreenhill** [comment]
perfect thanks.
