### ISSUE TITLE
Data updates.

### ISSUE THREAD

**Issue by HughP** [clld/glottolog3#39]
Where does one provide commentary about resources which have been auto tagged? For instance http://glottolog.org/resource/reference/id/138260 is tagged as idak1243: http://glottolog.org/resource/languoid/id/idak1243 Which is not correct as far as I can tell. but this issue tracker does not seem to be about data correction. Additionally the UI on the application does not seem to be requesting input from users.

**Comment by HedvigS** [comment]
Either in the issue tracker for glottlog data (https://github.com/clld/glottolog-data/issues) or by email, at each reference there is an alarm bell which send you to they email address and a pre-written text for corrupting "I found an error in xxx, it reads xxx it should read xxx".

**Comment by d97hah** [comment]
If it's about the data one can also just email me.

2015-01-18 9:58 GMT+01:00 Hedvig Skirgård <notifications@github.com>:
