### ISSUE TITLE
Provide top-level family in RDF representation of `Languoid`

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#46]
`Languoid` resources do now link to their immediate parent group with a `skos:broader` relation. But often, one is only interested in the top-level group containing a `Languoid`. This family should be linked via a [`gold:LanguageFamily`](http://linguistics-ontology.org/gold/2010/LanguageFamily) relation.

**Comment by xrotwang** [comment]
Turns out [`gold:LanguageFamily`](http://linguistics-ontology.org/gold/2010/LanguageFamily) isn't really a relation and [`gold:inLanguage`](http://linguistics-ontology.org/gold/2010/inLanguage) cannot be used between languages or language groupings. So we simply add another `skos:broader` relation which can be followed and if `rdf:type` of the dereferenced thing is `gold:LanguageFamily`, that's the top-level grouping.

**Comment by xflr6** [comment]
This can make it very hard for RDF users to retrieve the immediate parent of a languoid using RDF-tools.
IIUC `skos:broaderTransitive` would be the predicate to use, as `skos:broader` and its inverse `skos:narrower` [are only to be used to express direct relations](http://www.w3.org/TR/skos-reference/#semantic-relations).

**Comment by xrotwang** [comment]
@xflr6 good call! Should keep the issues for some time instead of implementing the first idea that comes to my mind :)

**Comment by xrotwang** [comment]
[deployed](http://glottolog.org/resource/languoid/id/jiar1240.rdf)
