### ISSUE TITLE
Use monster-replacements.json in BibTeX import

### ISSUE THREAD

**Issue by xflr6** [clld/glottolog3#48]
Adapt [match_obsolete_refs.py](https://github.com/clld/glottolog3/blob/master/glottolog3/scripts/match_obsolete_refs.py) to use the replacements calculated by `monster.py`.

**Comment by xrotwang** [comment]
@xflr6 where does `monster.py` write this information to?

**Comment by xflr6** [comment]
Into the [same directory](https://github.com/clld/glottolog-data/blob/master/scripts/monster.py#L58-L59) as the bibfile, so usually it should be `scripts/monster-replacements.json`.

**Comment by xrotwang** [comment]
Ah. I always look for files using `git status` :)
