### ISSUE TITLE
Make forms easier navigable adding tabindex attributes

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#51]
It would make life sooo much easier (and more
efficient) if the default position for the cursor was in the top right-hand
search box ("pr. Name / glcode / iso"), i.e.

   tabindex="1"

And even better if, on a Language Search page, a single tab moved the
cursor from this search box to the "Name (primary or alternative)" search
box, i.e.

   tabindex="2"

**Comment by xrotwang** [comment]
@stevepepper implemented and deployed on http://glottolog.org

**Comment by stevepepper** [comment]
Thanks, @xrotwang. Much appreciated. Looking forward to spending a new day with Glottolog today.
