### ISSUE TITLE
Include IANA language codes

### ISSUE THREAD

**Issue by nichtich** [clld/glottolog3#56]
The data contains ISO-639-3 code but for technical applications [IANA code](https://en.wikipedia.org/wiki/IETF_language_tag) is more important it's the official way to code languages in HTML, XML, and RDF among other applications. In most cases IANA codes derive from ISO-639-3 or ISO-639-1 but this is not always the case.

**Comment by xrotwang** [comment]
Reading up on [wikipedia](https://en.wikipedia.org/wiki/IETF_language_tag#ISO_639-3_and_ISO_639-1), there does not seem to be an automatic way to match. We are in the process of moving the data curation to a [github repository](https://github.com/clld/glottolog), so at least this will provide a mechanism to add this data in a collaborative way.

**Comment by xrotwang** [comment]
Another issue is that languages in Glottolog may not be in one-to-one correspondence with ISO-639-3 languages, so the IANA code would not be a property of a glottolog language, but a property of the associated ISO languages (if this is how the mapping is determined), which would complicate our data model somewhat.

In general, one of the reasons for the existence of Glottolog is that there is quite a bit of controversy about completeness and correctness of ISO-639-3 (and the underlying Ethnologue language clasification). So in all cases where Glottolog and Ethnologue are in conflict, assignment of a IANA code would have to be resolved manually.

**Comment by nichtich** [comment]
Yes, there is no automatic matching and matches can change. I'd like to use glottocodes as primary language identifiers but need IANA codes for technical applications.

My current source of mapping is Wikidata. Try this query to get Glottocode to ISO 639-1/2/3/5/6, IANA/IETF, and Ethnologue codes: http://tinyurl.com/ze9ocqs Maybe this is enough?

About your official data repository I am confused. <https://github.com/clld/glottolog> or <https://github.com/clld/glottolog-data>?

**Comment by xrotwang** [comment]
@nichtich yeah, it's a bit confusing. It used to be clld/glottolog-data but now moved to clld/glottolog 

The new data structure is a lot more transparent and hopefully this makes up for the initial confusion. If you clone the repository and install the included python client via `python setup.py install`, you can then access the repository data programmatically - which would also be the way to add IANA codes, I guess. We are still in the process of rolling out this new data curation setup, though. By september we hope to also have functionality to mint new glottocodes, thus providing a mechanism for people to add "their" languages in a way that allows merging into clld/glottolog via pull requests.

**Comment by nichtich** [comment]
Thanks for background. I'll focus on access via Wikidata and see back in autumn.

**Comment by xrotwang** [comment]
Moved to data repository: https://github.com/clld/glottolog/issues/86
