### ISSUE TITLE
Not so PURL afterall

### ISSUE THREAD

**Issue by bambooforest** [clld/glottolog3#58]
http://purl.org/sealang/fu1997descriptive.pdf

on:

http://glottolog.org/resource/reference/id/133055

maybe all the sealang stuff?

http://purl.org/sealang/evans2006origins.pdf

**Comment by xrotwang** [comment]
Yeah. And administration of redirects within PURL is just one point-of-failure. I read somewhere that the PURL system itself was at risc of being kicked out of OCLC's portfolio.

**Comment by xrotwang** [comment]
Issue reported at sealang
