### ISSUE TITLE
Dogon genealogical tree update

### ISSUE THREAD

**Issue by bambooforest** [clld/glottolog3#60]
Based on Heath's current intuition (language code [xxxxxxxx] indicates missing language or branch; for the former there may already be a Glottolog code with different canonical label, except Tommo So, this language should be added to Glottolog; see McPherson 2013: http://glottolog.org/resource/reference/id/317790):

```
 'Dogon [dogo1299]'
-- 'East Dogon [xxxxxxx]'
---- 'Toro Tegu [toro1253][dtt]'
---- 'Jamsay [jams1239][djm]'
---- 'Toro So [toro1252][dts]'
---- 'Tomo Kan [tomo1243][dtm]'
---- 'Southeast Dogon [xxxxxxx]'
------ 'Ben Tey [bent1238][dbt]'
------ 'Bankan Tey [bank1259][dbw]'
------ 'Nanga [nang1261][nzz]'
------ 'Togo Kan [togo1254]'
------ 'Tengou Kan [xxxxxxxx]'
------ 'Donno So [donn1239]'
------ 'Tommo So [xxxxxxxx]'
-- 'West Dogon [west2779]'
---- 'Yanda Dom [yand1257][dym]'
---- 'Tebul Ure [tebu1239][dtu]'
---- 'Najamba-Kindigue [bond1248][dbu]'
---- 'Tiranige Diga [tira1258][tde]'
---- 'Dogul Dom [dogu1235][dbg]'
---- 'Southwest Dogon [west2779]'
------ 'Ampari [ampa1238][aqd]'
------ 'Bunoge [buno1241][dgb]'
------ 'Mombo [momb1254][dmb]'
------ 'Penange [pena1270]'
```

Note (Heath, pc):
- Jamsay seems pretty close to Togo Kan so we might end up putting it in southeastern. 
- Seems like Dogul Dom and neighboring Donno So have converged secondarily in some respects.

**Comment by xrotwang** [comment]
@bambooforest I can't read newick :) Is the above correct?

**Comment by xrotwang** [comment]
@bambooforest Just leave any changes as comments on this issue, and I'll try to turn this into the prototype of a re-classification pull request :)

**Comment by xrotwang** [comment]
Where would [Tene Kan](http://glottolog.org/resource/languoid/id/tene1248) end up in the new classification? Your Togo Kan is currently a dialect. Should this be a language instead?

**Comment by xrotwang** [comment]
moved to clld/glottolog
