### ISSUE TITLE
Small table of the descriptive status of languages of the world on front page

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#61]
Hiya, 

Greetings from Samoa. I'm sitting here writing up a proceedings paper for a conference, and I wanted to quote some updated numbers on just how many languages are covered by at least a grammar or grammar sketch according to Glottolog.

I have some old numbers on that in various slides of mine and @d97hah, but they're all outdated. People really like like seeing these numbers though. Isn't there some quick nifty ways this could just be displayed at the glottolog front page? I know we're not using @xrotwang s visualisation (yet?) and that the GlottoVis is not to be spread publicly (when?), but could these simple facts just be in a table on the front page in the meantime? Like the one at the bottom of Robert's visualisation, just with more categories, like this (but with added endangerment status):

Type # Languages
< Grammar 2580
< Grammar sketch 1161
< Dictionary 212
< Phonology 106
< Text collection 26
< Wordlist 1073
< Ethnographic 78
< Minimal 21
   Unknown 263
All 5520

No interactive map, no fancy time slider. Just the table. Is that possible?

**Comment by xrotwang** [comment]
Possible in the sense of "technically feasible": yes. Possible in the sense of "will be implemented in the next couple of weeks": no. I'm a bit swamped right now.

**Comment by HedvigS** [comment]
No worries, it's not urgent. I still have the Forkel-descriptive-browser :) Which is.. linked to glottolog-data, right?

**Comment by xrotwang** [comment]
What do you mean by "linked"?

**Comment by HedvigS** [comment]
as in, when changes happens in glottolog-data is that reflected in the interactive map and tables there?

**Comment by xrotwang** [comment]
No. The maps and tables are fed from the database of the web app, which reflects the last release of glottolog-data.

**Comment by HedvigS** [comment]
That would seem to satisfy my idea of "linked", even if not directly.

**Comment by xrotwang** [comment]
I guess there was quite a bit of change [since February], but yes, it is linked. Note that the next version of Glottolog will be based on https://github.com/clld/glottolog due to our re-factoring/change of the data repository.

**Comment by HedvigS** [comment]
ok, understood. Thanks Robert!

**Comment by d97hah** [comment]
technically possible yes, but it shouldn't be done because of that paper I
never seem to be able to finish... all the best, H

2016-11-24 0:05 GMT+01:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xrotwang** [comment]
@d97hah can I read a draft of that paper?

**Comment by d97hah** [comment]
Sure, will pass one as soon as it's readable

2016-11-24 13:29 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by HedvigS** [comment]
Ok. A table like this wouldn't be much of a scoop thought, but I understand. I'll do as usual and consult the descriptive status maps and tables Robert set up.
Is there anything we can do to lighten your workload on this Harald?

**Comment by d97hah** [comment]
on this? no

2016-11-24 19:58 GMT+01:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Ok. I think both me and Robert are very keen to get this up, it's one of the coolest things about Glottolog to be able to do things like this. I know it takes a lot of work to pull all of this together, and I know you've put in a lot of work already. I guess I can't be of much help, but let me know if that changes.

**Comment by HedvigS** [comment]
I'm about to do a blogpost on the languages of descriptions in glottolog (https://docs.google.com/document/d/1t6uNoI5_TdbO3UKhiMPGEySJ8KbjK-cYAPYwFWS1xZ8/edit?usp=sharing ) and it'd be real neat to have an updated table of this.

**Comment by d97hah** [comment]
Learn python, download glottolog, use pyglottolog api and you can compute
it yourself!

2017-04-02 13:13 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Sorry, nevermind. I just thought it'd be a neat easy thing to point people to from the blog post, and I thought I'd check up on this issue and then I noticed the descriptive browser was down. Nevermind, forget about it.
