### ISSUE TITLE
Maps require OpenStreetMap attribution

### ISSUE THREAD

**Issue by scruss** [clld/glottolog3#62]
Maps — such as [Glottolog 2.7 - Scots](http://glottolog.org/resource/languoid/id/scot1243.bigmap.html#4/55.54/-6.00 "Glottolog 2.7 - Scots") — should have the requested [attribution](https://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F "attribution") "© OpenStreetMap contributors".

**Comment by xrotwang** [comment]
Reported upstream: https://github.com/clld/clld/issues/117
