### ISSUE TITLE
Map layers - some styles obsolete/unavailable

### ISSUE THREAD

**Issue by scruss** [clld/glottolog3#63]
Some of the map providers listed are no longer available, particularly the Mapquest tiles: http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by xrotwang** [comment]
Thanx for the notice. This is already fixed in the library glottolog3 uses, see https://github.com/clld/clld/issues/111
So it will be resolved with the next deploy.
