### ISSUE TITLE
World map languages

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog3#67]
Can there be a world map with languages under the languages tab/or elsewhere, with the languages coloured by top-genetic unit?

**Comment by HedvigS** [comment]
Imma guess "no"

**Comment by xrotwang** [comment]
@HedvigS As far as I'm concerned, there's nothing wrong with leaving un-implemented feature requests open. If I'm not going to implement it I'll close and label with "wontfix". Interpreting in-activity of developers as unwillingness will lead to frustration.

**Comment by HedvigS** [comment]
Oh ok. I didn't mean it as anything passive aggressive :), I just thought I should clear up my clutter from your reposes.

**Comment by agricolamz** [comment]
@HedvigS  I've made something [like that](https://agricolamz.github.io/families_by_area/). It is steel littlle bit dirty. But I can do it better if you need.

**Comment by HedvigS** [comment]
That's alright! Thanks @agricolamz . It's just a feature that is elsewhere on CLLD-sites that seemed to be missing for that tab. It's not very urgent at all.

**Comment by xrotwang** [comment]
This functionality is now available for the [Glottolog repository](https://github.com/clld/glottolog): After installing `pyglottolog` you can run:
```
glottolog htmlmap
```
and create a world map as specified here.
