### ISSUE TITLE
bibtex version of "how to cite glottolog" missing on website

### ISSUE THREAD

**Issue by LinguList** [clld/glottolog3#68]
compare with current display of "http://glottolog.org".

**Comment by xflr6** [comment]
What entrytype and bibkey should we use for this? `BibTex.render(request.dataset)` currently does this:
```
@book{glottolog,
  address   = {Jena},
  editor    = {Harald Hammarström and Robert Forkel and Martin Haspelmath},
  publisher = {Max Planck Institute for the Science of Human History},
  title     = {Glottolog 3.0},
  url       = {http://<hostname>/},
  year      = {2017}
}
```

**Comment by d97hah** [comment]
I'd prefer:
@misc{glottolog,
address = {Jena},

  author    = {Harald Hammarström and Robert Forkel and Martin Haspelmath},
  howpublished = {Max Planck Institute for the Science of Human History},
  title     = {Glottolog 3.0},
  url       = {http://<hostname>/ accesssed YYYY-MM-DD},
  year      = {2017}
}



2017-10-11 16:59 GMT+02:00 Sebastian Bank <notifications@github.com>:
