### ISSUE TITLE
Useful to show lgcode in languages box for a source

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog3#69]
I was looking at [this source](http://glottolog.org/resource/reference/id/478018) and the names in the text and the names on glottolog are very different so matching up languages to glottocodes was hard. However, this information is in the `lgcode` section of the bibtex file (which I could see on the `bibtex` tab:

```
lgcode     = {Lebo' Vo' in Long San = Mboh (a Kenyan lg) = Western Lowland Kenyah [ttw], Uma' Pawe = Eastern Lowland Kenyah [whk], Lepo' Gah, Lepo' Laang, Lepo' Sawa', Lepo' Tau = Kenyah-Mainstream [xkl], Badeng = Kenyah-Mainstream [xkl], Ngorek = Murik (Malaysia) [mxr], Long Naah Kayan = Baram Kayan [kys]},
  macro_area = {Papunesia},
```

It would be nice to have this more visible for non-technical users (who can't mentally parse bib format).

**Comment by xrotwang** [comment]
That's actually a regression - we used to have this info in the "Languages" box on the right hand side.

**Comment by d97hah** [comment]
So why did we take it away?

2017-03-29 10:59 GMT+02:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
Accidentally
Am 29.03.2017 18:59 schrieb "d97hah" <notifications@github.com>:

**Comment by xrotwang** [comment]
Fix will appear online after next deploy - probably end of next week.
