### ISSUE TITLE
Populate `Ref.language_note`

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#70]
Previously, `Ref.language_note` was filled with the content of the `lgcode` field of a BibTeX record. This isn't done so far for the new DB initialization. If we reinstitute it, though, we may want to cleanup/polish the format of these field - @d97hah  possibly even allow markdown?

**Comment by d97hah** [comment]
Sure

2017-03-30 9:08 GMT+02:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
@d97hah Does that mean you'd actually use this feature - i.e. make the comments more extensive? Other than the conversion before rendering on the web, there would also be another price for this more expressive syntax: the markdown link syntax `[label](url)` could possibly conflict with the syntax for language identifiers `[abc]`. So if we'd change to allowing markdown, I'd say we also switch the language identifiers to glottocodes to make them less ambiguous.

**Comment by d97hah** [comment]
No I wouldn't use markdown myself (don't know how I would need it).
[label](url) is syntactically distinguishable from [abc] I think, in that
sq brackets denote [abc] unless immediately followed by (.

2017-03-30 9:58 GMT+02:00 Robert Forkel <notifications@github.com>:
